### ISSUE TITLE
environment error

### ISSUE THREAD

**Issue by zhenyuanzhou** [zliucz/animate-your-word#2]
ResolvePackageNotFound:
  - numpy==1.22.3=py38hf6e8229_2
  - yaml==0.2.5=h7f98852_2
  - python==3.8.18=h955ad1f_0
  - cudatoolkit==11.8.0=h6a678d5_0
  - pip==22.3.1=py38h06a4308_0

And I'm using CUDA121

**Comment by ken-ouyang** [comment]
Hi, if the conda environment resolve fails, you can also manually install it using pip. E.g, pip install numpy==1.22.3. As you are using CUDA121, you may need to install the corresponding version of toolkits instead of the listed one.

**Comment by zhenyuanzhou** [comment]
OK, I solve the environment error but with new problem

Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    setup(name = 'diffvg',
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\install.py", line 87, in run
    self.do_egg_install()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 31, in run
    super().run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\build_ext.py", line 91, in run
    _build_ext.run(self)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
    self.build_extensions()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 39, in build_extension
    '-DPYTHON_LIBRARY=' + get_config_var('LIBDIR'),
TypeError: can only concatenate str (not "NoneType") to str

**Comment by zhenyuanzhou** [comment]
New problem when I'm installing the diffvg

Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    setup(name = 'diffvg',
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\install.py", line 87, in run
    self.do_egg_install()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 31, in run
    super().run()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\command\build_ext.py", line 91, in run
    _build_ext.run(self)
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
    self.build_extensions()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "F:\animate-your-word\dTypo\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 66, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "F:\animate-your-word\dTypo\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

**Comment by zliucz** [comment]
Hi. If you encountered difficulties in installing diffvg, please refer to its GitHub repo: https://github.com/BachiLi/diffvg. Also, all our testings are conducted in Linux. So, we suggest you switch to Linux if possible. Thank you.

**Comment by zhenyuanzhou** [comment]
Ok, another tough task
